language: julia

julia:
  - 0.4
  - 0.5
  - nightly

#script: # use the default script which is equivalent to the following
#    - julia -e 'versioninfo(); Pkg.init(); Pkg.clone(pwd()); Pkg.build("PowerLaws");Pkg.test("PowerLaws");'
